'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {GitBranch,ArrowLeft,Plus,FileText,Search,Check,ShieldCheck,ArrowUpLeft,Clock3,History,Library,Download,Loader2,RefreshCw,ExternalLink,Info,FolderOpen,Upload,Users,CheckCheck,Link2,ChevronLeft,ScanText} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {analysisPrecedesEdit} from '@/lib/tadarok/presentation';
import {exportForReview} from '@/lib/tadarok/export';
import type {WorkspaceState,Doc,Finding,Role} from '@/lib/tadarok/types';

const statusNames:Record<string,string>={pending:'تنتظر المراجعة',corrected:'عُدّلت · تنتظر الاعتماد',approved:'اعتمدت المراجعة',dismissed:'أُغلقت دون تعديل',referred:'محالة للمختص',stale:'تغيّر النص · أعد الفحص'};
const verdictNames:Record<string,string>={affected:'قد تتأثر',unaffected:'لا يظهر تأثرها',uncertain:'تحتاج تحققًا'};
const roleNames:Record<Role,string>={owner:'مسؤول المساحة',editor:'محرر',reviewer:'مراجع'};
const actionNames:Record<string,string>={documents_imported:'استيراد مكتبة نصية',document_added:'إضافة مادة',document_edited:'تعديل نص وإعادة فتح مراجعاته',correction_added:'تسجيل تصحيح مرجعي',analysis_finished:'انتهاء فحص الأثر',analysis_invalidated:'تغيّرت المكتبة أثناء الفحص',review_approve:'اعتماد المراجعة',review_dismiss:'إغلاق الملاحظة دون تعديل',review_refer:'إحالة للمختص',example_added:'إضافة مثال تدريبي',member_added:'تحديد صلاحية عضو'};
const formatDate=(v:string)=>new Intl.DateTimeFormat('ar-KW',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kuwait',numberingSystem:'latn'}).format(new Date(v));
const initialCorrection={title:'',oldText:'',newText:'',reference:'',referenceUrl:'',reason:''};
const initialDoc={title:'',body:'',kind:'منشور'};
type ApiState=WorkspaceState&{error?:string;selectedCorrectionId?:string};
type ModelContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown|Promise<unknown>},options:{signal:AbortSignal})=>unknown};

export default function Workspace({signedIn,signInPath,demoData,trial=false}:{signedIn:boolean;signInPath:string;demoData?:WorkspaceState;trial?:boolean}){
 const [data,setData]=useState<WorkspaceState|null>(demoData||null),[loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[analysisError,setAnalysisError]=useState('');
 const [busy,setBusy]=useState(''),[tab,setTab]=useState('corrections'),[selected,setSelected]=useState(''),[search,setSearch]=useState('');
 const [dialog,setDialog]=useState<'doc'|'correction'|'review'|'edit'|'members'|'batch'|'space'|null>(null),[docForm,setDocForm]=useState(initialDoc),[correctionForm,setCorrectionForm]=useState(initialCorrection);
 const [editing,setEditing]=useState<Doc|null>(null),[activeFinding,setActiveFinding]=useState<Finding|null>(null),[decision,setDecision]=useState('refer'),[note,setNote]=useState('');
 const [memberEmail,setMemberEmail]=useState(''),[memberRole,setMemberRole]=useState('editor'),[filter,setFilter]=useState('all');
 const [spaceName,setSpaceName]=useState('اختبار إضافي');
 const [batchDocs,setBatchDocs]=useState<typeof initialDoc[]>([]);
 const trialSession=useRef<Promise<Response>|null>(null);
 const stateRef=useRef(data);stateRef.current=data;
 const spaceId=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('space'):null;
 const apiPath=trial?'/api/try':'/api/tadarok';
 const endpoint=apiPath+(spaceId?'?space='+encodeURIComponent(spaceId):'');
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{if(trial){const session=await (trialSession.current??=fetch('/api/try/session',{method:'POST'}));if(!session.ok){trialSession.current=null;const failure=await session.json() as {error?:string};throw new Error(failure.error||'تعذر بدء التجربة.');}}const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json() as ApiState;if(!r.ok)throw new Error(d.error||'تعذر تحميل المساحة.');setData(d);setSelected(v=>v||d.corrections?.[0]?.id||'');}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل.');}finally{setLoading(false);}},[endpoint,trial]);
 useEffect(()=>{if(signedIn)void refresh();},[signedIn,refresh]);
 async function operate(action:string,payload:Record<string,unknown>={}){
 if(demoData)throw new Error('هذا مثال للعرض. افتح مساحة العمل لحفظ موادك وقراراتك.');
 if(!signedIn)throw new Error('سجّل الدخول لحفظ عملك.');
 const r=await fetch(apiPath,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,spaceId:stateRef.current?.space?.id||spaceId||undefined,...payload})});
 const d=await r.json() as ApiState;if(!r.ok)throw new Error(d.error||'تعذر تنفيذ العملية.');if(action==='create_space'&&d.space){window.location.assign('/?space='+encodeURIComponent(d.space.id));return d;}setData(d);if(d.selectedCorrectionId){setSelected(d.selectedCorrectionId);setTab('corrections');}return d as WorkspaceState;
 }
 async function run(action:string,payload:Record<string,unknown>={},close=true){if(busy)return;setBusy(action);if(action==='analyze')setAnalysisError('');try{let latest=stateRef.current;if(!latest?.space&&action!=='setup'){latest=await operate('setup');stateRef.current=latest;}await operate(action,payload);if(close)setDialog(null);toast.success(action==='analyze'?'اكتمل فحص الأثر. راجع المقترحات قبل اعتمادها.':'تم حفظ التغيير.');}catch(e){const message=e instanceof Error?e.message:'تعذر إكمال العملية.';if(action==='analyze'){setAnalysisError(message);await refresh();}toast.error(message);}finally{setBusy('');}}
 const current=data?.corrections.find(c=>c.id===selected)||data?.corrections[0];
 const findings=(data?.findings||[]).filter(f=>f.correction_id===current?.id);
 const currentRun=data?.runs.find(r=>r.id===current?.last_run_id);
 const unscanned=(data?.documents||[]).filter(d=>!findings.some(f=>f.document_id===d.id&&f.document_version===d.version)).length;
 const filteredFindings=findings.filter(f=>filter==='all'||(filter==='open'&&!['approved','dismissed'].includes(f.status))||(filter==='affected'&&f.verdict==='affected'));
 const pending=(data?.findings||[]).filter(f=>!['approved','dismissed'].includes(f.status)).length;
 const finished=(data?.findings||[]).filter(f=>['approved','dismissed'].includes(f.status)).length;
 const documents=(data?.documents||[]).filter(d=>(d.title+' '+d.body).includes(search));
 const canApprove=!data||data.actor.role==='owner'||data.actor.role==='reviewer';
 function newDoc(){setDocForm(initialDoc);setEditing(null);setActiveFinding(null);setDialog('doc');}
 function editDoc(doc:Doc,finding?:Finding){setDocForm({title:doc.title,body:doc.body,kind:doc.kind});setEditing(doc);setActiveFinding(finding||null);setNote('');setDialog('edit');}
 function review(f:Finding,what:string){setActiveFinding(f);setDecision(what);setNote('');setDialog('review');}
 function download(){if(!data)return;const content=JSON.stringify(exportForReview(data,!!demoData),null,2);const a=document.createElement('a');const url=URL.createObjectURL(new Blob([content],{type:'application/json;charset=utf-8'}));a.href=url;a.download='tadarok-review-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function upload(file:File|undefined){if(!file)return;if(!/\.txt$/i.test(file.name)||file.size>30000){toast.error('اختر ملف TXT بترميز UTF-8 وحجم حتى 30 KB.');return;}const body=(await file.text()).replace(/^\uFEFF/,'');if(body.length>3000){toast.error('الحد الأقصى للمادة 3000 حرف.');return;}setDocForm(v=>({...v,body,title:v.title||file.name.replace(/\.txt$/i,'')}));}
 async function uploadBatch(files:FileList|null){if(!files?.length)return;const list=Array.from(files);if(list.length>20||(data?.documents.length||0)+list.length>20){toast.error('الحد الأقصى 20 مادة في المكتبة.');return;}try{const next=await Promise.all(list.map(async file=>{if(!/\.txt$/i.test(file.name)||file.size>30000)throw new Error('يجب أن تكون الملفات TXT بترميز UTF-8 وحجم حتى 30 KB.');const body=(await file.text()).replace(/^\uFEFF/,'').trim();if(body.length<10||body.length>3000||body.includes('�'))throw new Error('تحقق من ترميز الملفات وطول النص: من 10 إلى 3000 حرف.');return {title:file.name.replace(/\.txt$/i,'').slice(0,100),body,kind:'مسودة'};}));setBatchDocs(next);}catch(e){toast.error(e instanceof Error?e.message:'تعذر قراءة الملفات.');}}
 async function loadTestLibrary(){if(busy)return;setBusy('load_test_library');try{
 if(demoData||!signedIn)throw new Error('افتح مساحة عملك أولًا.');
 if(data?.documents.length||data?.corrections.length)throw new Error('مكتبة الاختبار الكاملة تحتاج مساحة فارغة.');
 const response=await fetch('/evaluation/tadarok-test-library.json',{cache:'no-store'});
 if(!response.ok)throw new Error('تعذر جلب مكتبة الاختبار.');
 const fixture=await response.json() as {documents:Array<{title:string;body:string;kind:string}>;correction:Record<string,string>};
 if(!Array.isArray(fixture.documents)||fixture.documents.length!==20||!fixture.correction)throw new Error('ملف الاختبار غير مكتمل.');
 let active=stateRef.current;
 if(!active?.space){active=await operate('setup');stateRef.current=active;}
 active=await operate('import_documents',{documents:fixture.documents,confirmSynthetic:true});stateRef.current=active;
 await operate('add_correction',{...fixture.correction,confirmSynthetic:true});
 toast.success('أُضيفت 20 مادة مصطنعة وتصحيحها المرجعي. اضغط فحص الأثر لبدء تحليل حي.');
 }catch(e){toast.error(e instanceof Error?e.message:'تعذر تجهيز مكتبة الاختبار.');}finally{setBusy('');}}
 useEffect(()=>{const ctx=(document as Document&{modelContext?:ModelContext}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();
 const tools=[{name:'tadarok_read_workspace',title:'قراءة مساحة تدارك',description:'Read the current visible workspace documents, corrections, suggested findings, and review statuses. Does not perform new analysis or approve anything.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const s=stateRef.current;return s?{space:s.space,documents:s.documents,corrections:s.corrections,findings:s.findings,aiReady:s.aiReady}:{status:'not_loaded'};}},
 {name:'tadarok_start_correction',title:'بدء تصحيح جديد',description:'Open the visible new correction form. This only starts a form; it does not save, analyze, or approve content.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');flushSync(()=>{setCorrectionForm(initialCorrection);setDialog('correction');});return {status:'form_opened'};}}];
 for(const tool of tools)try{Promise.resolve(ctx.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}return ()=>controller.abort();},[]);
 return <div className={"app-shell "+(current?"has-content":"")} dir="rtl"><Toaster position="bottom-center" dir="rtl" theme="light" richColors/>
 <header className="topbar"><a className="brand" href="/" aria-label="تدارك الرئيسية"><span className="brand-mark"><GitBranch size={27}/></span><span className="brand-name">تدارك<span>متابعة أثر التصحيح</span></span></a><div className="header-side"><span className="private-label"><ShieldCheck size={15}/>مساحة المراجعة</span>{signedIn&&!demoData&&!trial&&<><select aria-label="اختيار مساحة المراجعة" disabled={!!busy} value={data?.space?.id||''} onChange={e=>window.location.assign('/?space='+encodeURIComponent(e.target.value))} style={{maxWidth:180,padding:8,borderRadius:8,border:'1px solid #d9e2d2',background:'#fff'}}>{!data?.space&&<option value="">مساحاتي</option>}{data?.spaces?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button variant="outline" disabled={!!busy||loading} onClick={()=>setDialog('space')}><Plus size={16}/>مساحة جديدة</Button></>}{signedIn&&!trial?<button className="avatar" aria-label="أعضاء المساحة" onClick={()=>setDialog('members')}>{data?.actor.name?.charAt(0)||'ت'}</button>:<Button asChild variant="outline"><a href={signInPath} target="_top">تسجيل الدخول</a></Button>}</div></header>
 <main className="main-wrap"><section className="intro"><div><div className="eyebrow"><span/>من المعلومة إلى كل ما بُني عليها</div><h1>صحّح الأصل<span className="accent-dot">.</span> تابع الأثر<span className="accent-dot">.</span></h1><p>اكتشف المواد التي قد تتأثر بتصحيح المعلومة<br className="desktop-br"/> واتخذ قرارًا واضحًا لكل نسخة.</p></div><div className="intro-actions"><Button size="lg" onClick={()=>{setCorrectionForm(initialCorrection);setDialog('correction');}}><Plus size={18}/>تصحيح جديد</Button><Button size="lg" variant="outline" onClick={newDoc}><FileText size={18}/>إضافة مادة</Button></div></section>
 {trial&&<div className="connection-note"><Info size={18}/><p><strong>تجربة فعلية بدون حساب.</strong> مساحة مستقلة لهذا المتصفح لمدة 24 ساعة. ابدأ بفحص الأثر ثم عدّل وراجع وصدّر السجل. حتى 20 فحصًا للجلسة ضمن السعة اليومية المشتركة. استخدم بيانات اصطناعية فقط؛ تُرسل النصوص إلى خدمة OpenAI عند الفحص. الأمثلة مصطنعة حول تصحيح مرجع حديث، دون نتائج مسبقة. صدّر عملك قبل انتهاء الجلسة.</p></div>}
 {demoData&&<div className="connection-note tour-note"><Info size={18}/><p><strong>جولة توضيحية.</strong> خمس مواد ونتائج معدّة مسبقًا لشرح المراجعة، وليست نتائج تحليل حي. لا تُحفظ التغييرات هنا.</p><a href="/">افتح مساحة عملك <ArrowUpLeft size={16}/></a></div>}
 {!signedIn&&!demoData&&<div className="connection-note"><Info size={18}/><p>جرّب الفحص والمراجعة بدون حساب، أو سجّل الدخول لحفظ عمل المؤسسة وإدارة أعضائها.</p><a href="/try">جرّب تدارك بدون تسجيل</a></div>}
 {signedIn&&data&&!data.aiReady&&<div className="connection-note"><Info size={18}/><p><strong>التحليل الدلالي ينتظر الربط.</strong> يمكنك حفظ المواد والتصحيحات وتجربة مسار المراجعة بالمثال التدريبي.</p></div>}
 {error&&<div className="error-note" role="alert"><p>{error}</p><Button variant="outline" onClick={refresh}>إعادة المحاولة</Button></div>}
 <div className="overview"><div><span className="stat-icon"><Library size={20}/></span><span><strong>{data?.documents.length||0}</strong><small>مادة في المكتبة</small></span></div><div><span className="stat-icon"><GitBranch size={20}/></span><span><strong>{data?.corrections.length||0}</strong><small>تصحيح مرجعي</small></span></div><div><span className="stat-icon amber"><Clock3 size={20}/></span><span><strong>{pending}</strong><small>ملاحظة مفتوحة</small></span></div><div><span className="stat-icon"><CheckCheck size={20}/></span><span><strong>{finished}</strong><small>مراجعة أُغلقت</small></span></div></div>
 <Tabs dir="rtl" value={tab} onValueChange={setTab}><div className="workspace-nav"><TabsList variant="line"><TabsTrigger value="corrections"><GitBranch/>التصحيحات</TabsTrigger><TabsTrigger value="library"><Library/>مكتبة المحتوى</TabsTrigger><TabsTrigger value="history"><History/>سجل القرارات</TabsTrigger></TabsList><Button variant="ghost" size="sm" onClick={download} disabled={!data?.space}><Download/>تصدير السجل</Button></div>
 <TabsContent value="corrections">
 {loading?<div className="empty-panel"><Loader2 className="animate-spin"/><p>جارٍ فتح مساحة العمل…</p></div>:!current?<div className="empty-panel first-empty"><span className="empty-symbol"><GitBranch size={36}/></span><h2>كل تصحيح بداية لأثر أوضح</h2><p>أضف موادك ثم أدخل النص السابق والتصحيح المرجعي.<br/>ستجتمع هنا المواد المقترحة للمراجعة وقراراتك بشأنها.</p><div className="empty-actions"><Button onClick={()=>{setCorrectionForm(initialCorrection);setDialog('correction');}}>أضف أول تصحيح <ArrowLeft/></Button><Button variant="outline" disabled={!!busy||!!data?.documents.length} onClick={()=>void loadTestLibrary()}><ScanText/>تعبئة تجربة 20 مادة</Button></div><small>عينة مصطنعة دون نتائج مسبقة. <a href="/demo">شاهد جولة توضيحية</a></small></div>:<div className="case-layout"><aside className="case-list"><div className="section-kicker">ملفات التصحيح <span>{data?.corrections.length}</span></div>{data?.corrections.map(c=><button key={c.id} onClick={()=>{setSelected(c.id);setFilter('all');}} className={'case-nav-item '+(c.id===current.id?'active':'')}><span className="case-small-icon"><FileText size={18}/></span><span><strong>{c.title}</strong><small>{formatDate(c.created_at)}{c.is_demo?' · تدريبي':''}</small></span><ChevronLeft size={16}/></button>)}<div className="side-note"><ShieldCheck size={23}/><p>التحليل يقترح مواضع المراجعة.<br/>قرار التصحيح يبقى للمراجع.</p></div></aside><div className="case-main"><section className="source-card"><div className="source-heading"><div><span className="section-kicker">التصحيح المرجعي</span><h2>{current.title}</h2></div><span className="badge neutral">{current.is_demo?'مثال تدريبي':'أدخله المستخدم'}</span></div><div className="comparison"><div className="previous"><span>النص السابق</span><p>{current.old_text}</p></div><div className="corrected"><span><Check size={14}/>النص المصحح</span><p>{current.new_text}</p></div></div><div className="source-reference"><Link2 size={17}/><div><strong>{current.reference}</strong><p>{current.reason}</p></div>{current.reference_url&&<a href={current.reference_url} target="_blank" rel="noopener noreferrer" aria-label="فتح المرجع"><ExternalLink size={17}/></a>}</div></section>
 <div className="findings-heading"><div><h2>المواد المرتبطة بالتصحيح <span>{findings.length}</span></h2><p>{currentRun?.engine==='illustrative-example'?'نتائج توضيحية معدة مسبقًا · لا تمثل قياسًا لدقة التحليل':currentRun?.status==='completed'?'مقترحات من آخر فحص · يلزم قرار بشري لكل مادة':'ابدأ الفحص لاقتراح مواضع المراجعة داخل مكتبتك'}</p></div><Button onClick={()=>run('analyze',{id:current.id},false)} disabled={!!busy||!data?.aiReady||!data.documents.length}>{busy==='analyze'?<Loader2 className="animate-spin"/>:<RefreshCw size={16}/>} {busy==='analyze'?'جارٍ فحص الأثر…':'فحص الأثر'}</Button></div>
 {currentRun&&unscanned>0&&<div className="connection-note"><Info size={18}/><p>توجد {unscanned} مادة جديدة أو متغيرة لم يشملها آخر فحص. أعد فحص الأثر لتحديث النتائج.</p></div>}
 {analysisError&&<div className="error-note" role="alert"><Info size={18}/><p>{analysisError} المواد والتصحيح محفوظان. {findings.length>0?'النتائج الظاهرة أدناه من آخر فحص ناجح؛ لم تُحدّث بهذه المحاولة.':'لم تُحفظ نتائج لهذه المحاولة.'}</p></div>}
 {!data?.aiReady&&<p className="inline-hint">زر الفحص يتفعّل بعد ربط خدمة التحليل. النتائج التدريبية تظل مميزة بوضوح.</p>}
 {data?.aiReady&&<p className="inline-hint">عند الفحص تُرسل نصوص المكتبة والتصحيح إلى خدمة التحليل. استخدم مواد مصرحًا لك بمراجعتها.</p>}
 {findings.length>0&&<div className="filter-row"><Select dir="rtl" value={filter} onValueChange={setFilter}><SelectTrigger aria-label="تصفية الملاحظات"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">كل المواد</SelectItem><SelectItem value="open">المراجعات المفتوحة</SelectItem><SelectItem value="affected">يُحتمل تأثرها</SelectItem></SelectContent></Select><span>{filteredFindings.length} من المواد</span></div>}
 <div className="findings-list">{filteredFindings.map(f=>{const doc=data?.documents.find(d=>d.id===f.document_id);if(!doc)return null;const historical=analysisPrecedesEdit(f,doc,data?.events||[]);const stale=f.status==='stale'||f.document_version!==doc.version;return <article className={'finding-card '+(stale?'is-stale':'')} key={f.id}><header><div className="finding-title"><span className={'finding-icon '+f.verdict}>{f.verdict==='affected'?<GitBranch size={19}/>:f.verdict==='unaffected'?<Check size={19}/>:<Search size={19}/>}</span><div><h3>{doc.title}</h3><span>{doc.kind} · النسخة <bdi>{doc.version}</bdi></span></div></div><span className={'badge '+f.verdict}>{historical?'الفحص السابق: ':''}{verdictNames[f.verdict]}</span></header>{f.quote&&<blockquote><small className="quote-label">{historical?'شاهد الفحص قبل التعديل':'العبارة المرصودة عند الفحص'}</small>{f.quote}</blockquote>}<p className="finding-reason">{historical?'سبب التنبيه قبل التعديل: ':''}{f.reason}</p>{historical&&<p className="analysis-history-note">عُدّل النص بعد هذا الفحص. النتيجة والشاهد أعلاه يخصان النص السابق؛ اقرأ النص الحالي أدناه وقرار مراجعته.</p>}<details className="evidence-context" open={historical?true:undefined}><summary>{historical?'النص الحالي بعد التعديل':'قراءة المادة كاملة'} · النسخة <bdi>{doc.version}</bdi></summary><p style={{whiteSpace:"pre-wrap",lineHeight:1.9}}>{doc.body}</p></details><footer><span className={'review-status status-'+f.status}><span/>{statusNames[stale?'stale':f.status]}</span><div className="finding-actions">{!stale&&<><Button variant="ghost" size="sm" disabled={!!busy} onClick={()=>editDoc(doc,f)}>تعديل النص</Button><Button variant="ghost" size="sm" disabled={!!busy} onClick={()=>review(f,'refer')}>إحالة</Button>{canApprove&&(f.status==='corrected'||f.verdict==='unaffected')&&f.status!=='approved'?<Button size="sm" variant="outline" onClick={()=>review(f,'approve')}>اعتماد المراجعة</Button>:f.status!=='dismissed'&&f.status!=='approved'?<Button size="sm" variant="outline" onClick={()=>review(f,'dismiss')}>لا ينطبق التنبيه</Button>:null}</>}{stale&&<Button variant="outline" size="sm" onClick={()=>editDoc(doc)}>فتح النسخة الحالية</Button>}</div></footer>{f.note&&<div className="review-note"><strong>{f.reviewed_by}</strong><span>{f.note}</span>{f.reviewed_at&&<time>{formatDate(f.reviewed_at)}</time>}</div>}</article>})}
 {!findings.length&&<div className="empty-panel small"><FolderOpen size={30}/><h3>لم يبدأ فحص هذا التصحيح بعد</h3><p>أضف المواد إلى المكتبة ثم شغّل فحص الأثر.</p><Button variant="outline" onClick={()=>setTab('library')}>فتح المكتبة</Button></div>}
 </div></div></div>}
 </TabsContent>
 <TabsContent value="library"><div className="section-heading"><div><h2>مكتبة المحتوى</h2><p>النصوص التي تبحث فيها عن أثر التصحيح. حتى 20 مادة و3000 حرف لكل مادة.</p></div><div className="library-tools"><label className="searchbox"><Search size={17}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث في المكتبة" aria-label="ابحث في المكتبة"/></label><Button variant="outline" onClick={()=>{setBatchDocs([]);setDialog('batch');}}><Upload/>رفع ملفات</Button><Button onClick={newDoc}><Plus/>إضافة مادة</Button></div></div><a href="/evaluation/tadarok-test-library.zip" download className="benchmark-link"><Download size={14}/>مكتبة اختبار مصطنعة · 20 ملفًا وتعليمات القياس</a><div className="document-grid">{documents.map(d=><article key={d.id} className="document-card"><div className="doc-top"><span className="doc-icon"><FileText size={21}/></span><span className="badge neutral">{d.kind}</span></div><h3>{d.title}</h3><p>{d.body}</p><footer><span>نسخة <bdi>{d.version}</bdi>{d.is_demo?' · تدريبي':''}</span><Button size="sm" variant="ghost" onClick={()=>editDoc(d)}>فتح المادة <ArrowUpLeft size={15}/></Button></footer></article>)}</div>{!documents.length&&<div className="empty-panel"><Library size={32}/><h2>{search?'لا توجد نتيجة مطابقة':'مكتبتك تبدأ بأول مادة'}</h2><p>الصق نصًا عربيًا أو ارفع ملف TXT لتضيفه إلى مساحة المراجعة.</p><Button onClick={newDoc}>إضافة مادة <Plus/></Button>{signedIn&&!demoData&&!data?.corrections.length&&<Button variant="outline" disabled={!!busy} onClick={()=>void loadTestLibrary()}><ScanText/>تعبئة تجربة 20 مادة مصطنعة</Button>}</div>}</TabsContent>
 <TabsContent value="history"><div className="section-heading"><div><h2>سجل القرارات</h2><p>من راجع النص ومتى تغيّر. يعرض السجل والتصدير آخر 150 حدثًا كحد أقصى؛ وتبقى الأحداث الأقدم محفوظة في قاعدة البيانات.</p></div><Button variant="outline" onClick={download} disabled={!data?.events.length}><Download/>تصدير</Button></div><div className="audit-list">{data?.events.map(e=><AuditRow key={e.id} event={e}/>)}{!data?.events.length&&<div className="empty-panel"><History size={30}/><h2>السجل جاهز لأول خطوة</h2><p>ستظهر هنا إضافة المواد والتصحيحات وقرارات المراجعة.</p></div>}</div></TabsContent></Tabs>
 <footer className="page-footer"><span>تدارك · من التصحيح إلى الاطمئنان على كل نسخة</span><span>نسخة التحدي: مواد اصطناعية أو مجهولة الهوية بالكامل فقط</span></footer><p style={{fontSize:14,marginTop:24}}><a href="/transparency">المصادر وحدود التحليل والخصوصية</a></p></main>
 <Dialog open={dialog==='doc'||dialog==='edit'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent dir="rtl" className="form-dialog"><DialogHeader><DialogTitle>{dialog==='edit'?'تحرير المادة':'إضافة مادة للمكتبة'}</DialogTitle><DialogDescription>{dialog==='edit'?'أي تغيير يعيد المراجعات السابقة لهذه المادة إلى قائمة المراجعة.':'نص عربي قصير ضمن مكتبتك. يُحفظ النص في مساحة العمل.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void run(dialog==='edit'?'edit_document':'add_document',{...docForm,confirmSynthetic:true,id:editing?.id,version:editing?.version,findingId:activeFinding?.id,documentVersion:activeFinding?.document_version,expectedStatus:activeFinding?.status,expectedReviewedAt:activeFinding?.reviewed_at,note});}}><label>عنوان المادة<Input required maxLength={100} value={docForm.title} onChange={e=>setDocForm(v=>({...v,title:e.target.value}))}/></label>{dialog==='doc'&&<div className="form-columns"><label>نوع المادة<Select dir="rtl" value={docForm.kind} onValueChange={kind=>setDocForm(v=>({...v,kind}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['منشور','مقال','ملخص','نص فيديو','مسودة'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label><label className="upload-label"><Upload size={18}/>رفع ملف TXT<input type="file" accept=".txt,text/plain" onChange={e=>void upload(e.target.files?.[0])}/></label></div>}<label>نص المادة<Textarea required minLength={10} maxLength={3000} rows={8} value={docForm.body} onChange={e=>setDocForm(v=>({...v,body:e.target.value}))}/><span className="char-count"><bdi>{docForm.body.length}/3000</bdi></span></label>{activeFinding&&<label>سبب التعديل<Input required minLength={3} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="ما الذي تغير بناءً على المرجع؟"/></label>}<label className="data-confirm"><input type="checkbox" required/>أؤكد أن المادة اصطناعية أو مجهولة الهوية بالكامل، ولا تتضمن محادثات أو سجلات حقيقية للمستفيدين.</label><div className="form-footer"><Button type="submit" disabled={!!busy}>{busy?<Loader2 className="animate-spin"/>:<Check/>}حفظ المادة</Button><Button type="button" variant="ghost" disabled={!!busy} onClick={()=>setDialog(null)}>إلغاء</Button></div></form></DialogContent></Dialog>
 <Dialog open={dialog==='correction'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent dir="rtl" className="form-dialog wide"><DialogHeader><DialogTitle>تسجيل تصحيح مرجعي</DialogTitle><DialogDescription>أدخل التصحيح الذي تريد تتبّع أثره. النظام يبحث عن مواضع المراجعة بناءً عليه.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void run('add_correction',{...correctionForm,confirmSynthetic:true});}}><label>عنوان التصحيح<Input required maxLength={120} value={correctionForm.title} onChange={e=>setCorrectionForm(v=>({...v,title:e.target.value}))} placeholder="مثال: تصحيح مرجع اقتباس في مواد التعليم"/></label><div className="form-columns"><label>النص السابق<Textarea required minLength={5} maxLength={2000} rows={5} value={correctionForm.oldText} onChange={e=>setCorrectionForm(v=>({...v,oldText:e.target.value}))}/></label><label>النص المصحح<Textarea required minLength={5} maxLength={2000} rows={5} value={correctionForm.newText} onChange={e=>setCorrectionForm(v=>({...v,newText:e.target.value}))}/></label></div><label>المرجع المعتمد للتصحيح<Input required minLength={3} maxLength={600} value={correctionForm.reference} onChange={e=>setCorrectionForm(v=>({...v,reference:e.target.value}))} placeholder="اسم الكتاب ورقم الموضع أو مرجع قرار المراجعة"/></label><label>رابط المرجع <span className="optional">اختياري</span><Input type="url" dir="ltr" maxLength={600} value={correctionForm.referenceUrl} onChange={e=>setCorrectionForm(v=>({...v,referenceUrl:e.target.value}))} placeholder="https://"/></label><label>سبب التصحيح<Textarea required minLength={3} maxLength={1000} rows={2} value={correctionForm.reason} onChange={e=>setCorrectionForm(v=>({...v,reason:e.target.value}))}/></label><label className="data-confirm"><input type="checkbox" required/>أؤكد أن المادة اصطناعية أو مجهولة الهوية بالكامل، ولا تتضمن محادثات أو سجلات حقيقية للمستفيدين.</label><div className="form-footer"><Button disabled={!!busy} type="submit">{busy?<Loader2 className="animate-spin"/>:<Plus/>}حفظ التصحيح</Button><Button type="button" variant="ghost" onClick={()=>setDialog(null)} disabled={!!busy}>إلغاء</Button></div></form></DialogContent></Dialog>
 <Dialog open={dialog==='review'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent dir="rtl" className="form-dialog"><DialogHeader><DialogTitle>{decision==='approve'?'اعتماد المراجعة':decision==='dismiss'?'إغلاق الملاحظة دون تعديل':'إحالة إلى المختص'}</DialogTitle><DialogDescription>{decision==='refer'?'تُسجل الإحالة في مساحة العمل ليطلع عليها المراجع. لا تُرسل رسالة خارجية.':'سيُحفظ اسمك والقرار ونسخة النص التي راجعتها.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void run('review',{id:activeFinding?.id,decision,note,documentVersion:activeFinding?.document_version,expectedStatus:activeFinding?.status,expectedReviewedAt:activeFinding?.reviewed_at});}}><label>{decision==='refer'?'السؤال الذي يحتاج مراجعة':'سبب القرار'}<Textarea required minLength={3} maxLength={1000} rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder={decision==='refer'?'أحتاج مراجعة صلة هذه العبارة بالتصحيح المرجعي…':'وضح ما راجعته ولماذا اتخذت هذا القرار…'}/></label><div className="form-footer"><Button type="submit" disabled={!!busy}>{busy?<Loader2 className="animate-spin"/>:<Check/>}تسجيل القرار</Button><Button type="button" variant="ghost" onClick={()=>setDialog(null)} disabled={!!busy}>إلغاء</Button></div></form></DialogContent></Dialog>
 <Dialog open={dialog==='batch'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent dir="rtl" className="form-dialog"><DialogHeader><DialogTitle>رفع مكتبة نصية</DialogTitle><DialogDescription>اختر ملفات TXT بترميز UTF-8. الحد الأقصى للمكتبة 20 مادة، و3000 حرف لكل مادة.</DialogDescription></DialogHeader><label className="batch-upload"><Upload size={27}/><span>اختر ملفاتك النصية</span><small>يمكن اختيار أكثر من ملف</small><input type="file" multiple accept=".txt,text/plain" onChange={e=>void uploadBatch(e.target.files)}/></label>{batchDocs.length>0&&<><div className="batch-list">{batchDocs.map((d,i)=><div key={i}><span>{d.title}</span><small>{d.body.length} حرف</small></div>)}</div><form onSubmit={e=>{e.preventDefault();void run('import_documents',{documents:batchDocs,confirmSynthetic:true});}}><label className="data-confirm"><input type="checkbox" required/>أؤكد أن المادة اصطناعية أو مجهولة الهوية بالكامل، ولا تتضمن محادثات أو سجلات حقيقية للمستفيدين.</label><div className="form-footer"><Button type="submit" disabled={!!busy}>{busy?<Loader2 className="animate-spin"/>:<Check/>}حفظ {batchDocs.length} مادة</Button><Button type="button" variant="ghost" onClick={()=>setDialog(null)} disabled={!!busy}>إلغاء</Button></div></form></>}</DialogContent></Dialog>
 <Dialog open={dialog==='space'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent dir="rtl" className="form-dialog"><DialogHeader><DialogTitle>إنشاء مساحة مراجعة</DialogTitle><DialogDescription>مكتبة وتصحيحات وسجل قرارات مستقل. يمكنك الرجوع لمساحاتك من القائمة أعلى الصفحة.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void run('create_space',{name:spaceName});}}><label>اسم المساحة<Input required minLength={2} maxLength={80} value={spaceName} onChange={e=>setSpaceName(e.target.value)}/></label><div className="form-footer"><Button disabled={!!busy} type="submit">إنشاء المساحة</Button></div></form></DialogContent></Dialog>
 <Dialog open={dialog==='members'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent dir="rtl" className="form-dialog"><DialogHeader><DialogTitle>أعضاء مساحة المراجعة</DialogTitle><DialogDescription>تُحفظ القرارات باسم صاحب الحساب الفعلي ودوره داخل المساحة.</DialogDescription></DialogHeader>{data&&<div className="current-member"><span className="avatar">{data.actor.name.charAt(0)}</span><div><strong>{data.actor.name}</strong><p>{roleNames[data.actor.role]}</p></div></div>}{data?.actor.role==='owner'&&<><p className="inline-hint">تحديد الدور هنا لا يرسل دعوة. يحتاج العضو أيضًا إلى صلاحية فتح رابط الموقع من إعدادات المشاركة.</p>{data.members.map(m=><div className="member-row" key={m.id}><span dir="ltr">{m.email}</span><span className="badge neutral">{roleNames[m.role]}</span></div>)}<form onSubmit={e=>{e.preventDefault();void run('add_member',{email:memberEmail,role:memberRole},false);}}><label>البريد الإلكتروني<Input type="email" required dir="ltr" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)}/></label><label>الدور<Select dir="rtl" value={memberRole} onValueChange={setMemberRole}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="editor">محرر</SelectItem><SelectItem value="reviewer">مراجع</SelectItem></SelectContent></Select></label><Button type="submit" disabled={!!busy}><Users size={16}/>حفظ الدور</Button></form>{data.space&&<Button variant="outline" onClick={()=>{void navigator.clipboard.writeText(location.origin+'/?space='+data.space!.id).then(()=>toast.success('نُسخ رابط المساحة.'),()=>toast.error('تعذر النسخ.'));}}><Link2 size={16}/>نسخ رابط المساحة</Button>}</>}{!data&&<p>سجّل الدخول أولًا لفتح المساحة.</p>}</DialogContent></Dialog>
 </div>;
}
function AuditRow({event:e}:{event:WorkspaceState['events'][number]}){let details:Record<string,unknown>={};try{details=JSON.parse(e.details);}catch{}return <article className="audit-row"><span className="audit-dot"><History size={16}/></span><div className="audit-content"><div><h3>{actionNames[e.action]||e.action}</h3><time>{formatDate(e.created_at)}</time></div><p><strong>{e.actor_name}</strong> · {roleNames[e.actor_role as Role]||e.actor_role}</p>{!!(details.title||details.documentTitle||details.note||details.notice)&&<p className="audit-description">{String(details.title||details.documentTitle||details.note||details.notice)}</p>}{typeof details.fromVersion==='number'&&<span className="badge neutral">النسخة {details.fromVersion} ← {String(details.toVersion)}</span>}<details><summary>تفاصيل القرار</summary><pre dir="auto">{JSON.stringify(details,null,2)}</pre></details></div></article>}
