import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const spaces = sqliteTable('spaces', { id:text('id').primaryKey(), ownerId:text('owner_id').notNull(), name:text('name').notNull(), createdAt:text('created_at').notNull() },t=>[index('spaces_owner').on(t.ownerId)]);
export const members = sqliteTable('members', { id:text('id').primaryKey(), spaceId:text('space_id').notNull().references(()=>spaces.id), email:text('email').notNull(), role:text('role').notNull() },t=>[uniqueIndex('members_space_email').on(t.spaceId,t.email),index('members_email').on(t.email)]);
export const documents = sqliteTable('documents',{id:text('id').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id), title:text('title').notNull(),body:text('body').notNull(),kind:text('kind').notNull(),version:integer('version').notNull().default(1),mutationId:text('mutation_id').notNull(),isDemo:integer('is_demo').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('documents_space').on(t.spaceId)]);
export const corrections = sqliteTable('corrections',{id:text('id').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id),title:text('title').notNull(),oldText:text('old_text').notNull(),newText:text('new_text').notNull(),reference:text('reference').notNull(),referenceUrl:text('reference_url').notNull(),reason:text('reason').notNull(),lastRunId:text('last_run_id'),isDemo:integer('is_demo').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('corrections_space').on(t.spaceId)]);
export const runs = sqliteTable('runs',{id:text('id').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id),correctionId:text('correction_id').notNull().references(()=>corrections.id),engine:text('engine').notNull(),status:text('status').notNull(),actor:text('actor').notNull(),docCount:integer('doc_count').notNull(),elapsedMs:integer('elapsed_ms').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('runs_correction').on(t.correctionId)]);
export const findings=sqliteTable('findings',{id:text('id').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id),correctionId:text('correction_id').notNull().references(()=>corrections.id),runId:text('run_id').notNull().references(()=>runs.id),documentId:text('document_id').notNull().references(()=>documents.id),documentVersion:integer('document_version').notNull(),quote:text('quote').notNull(),reason:text('reason').notNull(),verdict:text('verdict').notNull(),status:text('status').notNull().default('pending'),note:text('note').notNull().default(''),reviewedBy:text('reviewed_by').notNull().default(''),reviewedAt:text('reviewed_at'),createdAt:text('created_at').notNull()},t=>[index('findings_space_doc').on(t.spaceId,t.documentId),index('findings_run').on(t.runId)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id),entityId:text('entity_id').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),actorRole:text('actor_role').notNull(),action:text('action').notNull(),details:text('details').notNull(),createdAt:text('created_at').notNull()},t=>[index('events_space_created').on(t.spaceId,t.createdAt)]);

export const guestSessions=sqliteTable('guest_sessions',{tokenHash:text('token_hash').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('guest_created').on(t.createdAt)]);
export const guestAnalysisBudget=sqliteTable('guest_analysis_budget',{id:text('id').primaryKey(),spaceId:text('space_id').notNull().references(()=>spaces.id),createdAt:text('created_at').notNull()},t=>[index('guest_budget_space').on(t.spaceId),index('guest_budget_created').on(t.createdAt)]);
